services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
            - ./storage:/var/www/storage
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - laravel
        ports:
            - "9000:9000"
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

    webserver:
        image: nginx:alpine
        depends_on:
            - app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: netshow
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
